# Generated by Django 4.2.2 on 2023-07-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
